import 'package:fl_chart/fl_chart.dart';
import 'package:intl/intl.dart';
import 'package:meta_auction/Models/watch.dart';



List<Watch> wat = [
  Watch(
      name:'Lorem ipsum',
      brand:'Rolex',
      year:2022,
      condition:'New',
      dialColor:'Silver',
      metal:'Steel',
      status:'Returned',
      lastBid:'20.000 USD',
      country:'USA',
      date:DateTime.now(),
      image: 'assets/images/watch.png',
      favorite:false ,
      topSelling: true,
      auctioned: false,
  ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: false,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
        topSelling: false,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
        topSelling: true,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: false,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
        topSelling: false,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: false,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
        topSelling: false,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: false,
        auctioned: false,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:true ,
        topSelling: true,
        auctioned: true,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
        topSelling: false,
        auctioned: true,
    ),
];

List<FlSpot> weekLists = [
    FlSpot(0, 1),
    FlSpot(1, 1.5),
    FlSpot(2, 1),
    FlSpot(3, 3.4),
    FlSpot(4, 2),
    FlSpot(5, 2.2),
    FlSpot(6, 1),
];

List<FlSpot> monthLists = [
    FlSpot(0, 1),
    FlSpot(1, 1.5),
    FlSpot(2, 1),
    FlSpot(3, 3.4),
    FlSpot(4, 2),
    FlSpot(5, 2.2),
    FlSpot(6, 1),
    FlSpot(7, 1.5),
    FlSpot(8, 1),
    FlSpot(9, 3.4),
    FlSpot(10, 2),
    FlSpot(11, 2.2),
];

List<FlSpot> yearLists = [
    FlSpot(0, 1),
    FlSpot(1, 1.5),
    FlSpot(2, 0.5),
];