import 'package:intl/intl.dart';
import 'package:meta_auction/Models/watch.dart';



List<Watch> wat = [
  Watch(
      name:'Lorem ipsum',
      brand:'Rolex',
      year:2022,
      condition:'New',
      dialColor:'Silver',
      metal:'Steel',
      status:'Returned',
      lastBid:'20.000 USD',
      country:'USA',
      date:DateTime.now(),
      image: 'assets/images/watch.png',
      favorite:false ,
  ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
    ),
    Watch(
        name:'Lorem ipsum',
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialColor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastBid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        image: 'assets/images/watch.png',
        favorite:false ,
    ),
];