import 'package:meta_auction/model/brand_details.dart';
import 'package:intl/intl.dart';
DateTime now = DateTime.now();
String formattedDate = DateFormat('EEE d MMM kk:mm ').format(DateTime.now());

List<BrandDetails> BrDetails = [
  BrandDetails(
      brand:'Rolex',
      year:'2022',
      condition:'New',
      dialcolor:'Silver',
      metal:'Steel',
      status:'Returned',
      lastbid:'20.000 USD',
      country:'USA',
      date:DateTime.now(),
      images: 'assets/images/watches.png',
      favorite:false ,
  ),
    BrandDetails(
        brand:'Rovina',
        year:'2021',
        condition:'New',
        dialcolor:'Black',
        metal:'Steel',
        status:'Returned',
        lastbid:'1000 USD',
        country:'Italy',
        date:DateTime.now(),
        images: 'assets/images/watches.png',
        favorite:true ,
    ),
    BrandDetails(
        brand:'Rolex',
        year:'2022',
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images:'assets/images/watches.png' ,
        favorite:false ,
    ),
    BrandDetails(
        brand:'Rolex',
        year:'2022',
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images:'assets/images/watches.png' ,
        favorite:true ,
    ),
    BrandDetails(
        brand:'Rolex',
        year:'2022',
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images: 'assets/images/watches.png',
        favorite: true,
    ),
];