import 'package:meta_auction/model/watch.dart';
import 'package:intl/intl.dart';
DateTime now = DateTime.now();
// DateFormat formattedDate = DateFormat('EEE d MMM');

List<Watch> wat = [
  Watch(
      brand:'Rolex',
      year:2022,
      condition:'New',
      dialcolor:'Silver',
      metal:'Steel',
      status:'Returned',
      lastbid:'20.000 USD',
      country:'USA',
      date:DateTime.now(),
      images: 'assets/images/watches.png',
      favorite:false ,
  ),
    Watch(
        brand:'Rovina',
        year:2022,
        condition:'New',
        dialcolor:'Black',
        metal:'Steel',
        status:'Returned',
        lastbid:'1000 USD',
        country:'Italy',
        date:DateTime.now(),
        images: 'assets/images/watches.png',
        favorite:true ,
    ),
    Watch(
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images:'assets/images/watches.png' ,
        favorite:false ,
    ),
    Watch(
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images:'assets/images/watches.png' ,
        favorite:true ,
    ),
    Watch(
        brand:'Rolex',
        year:2022,
        condition:'New',
        dialcolor:'Silver',
        metal:'Steel',
        status:'Returned',
        lastbid:'20.000 USD',
        country:'USA',
        date:DateTime.now(),
        images: 'assets/images/watches.png',
        favorite: true,
    ),
];